---

- name: Update repositories cache and install "gnome-shell-extensions" package
  apt:
    pkg: gnome-shell-extensions
    state: latest
    update_cache: yes
    cache_valid_time: "{{ APT_CACHE_VALID_TIME }}"
    
- name: Update repositories cache and install "chrome-gnome-shell" package
  apt:
    pkg: chrome-gnome-shell
    state: latest
    update_cache: yes
    cache_valid_time: "{{ APT_CACHE_VALID_TIME }}"

- name: Install Firefox extension "gnome-shell-integration"
  pause:
    prompt: 'Please install manually Firefox extension "gnome-shell-integration". When you are done, please press [Return] to continue. Press [Ctrl+C] and then [A] to abort'

- name: Upgrade all packages to the latest version
  apt:
    pkg: "*"
    state: latest
    cache_valid_time: "{{ APT_CACHE_VALID_TIME }}"