---


- name: Install Oh My ZSH
  become: yes
  shell: "curl -L http://install.ohmyz.sh | sh creates=~/.oh-my-zsh"
  tags: ohmyzsh

- name: Copy custom template
  template: 
    src: zshrc.j2
    dest: ~/.zshrc
  tags: ohmyzsh

- name: Set chsh
  become_user: "{{ ansible_env.USER }}"
  shell: 'chsh -s /bin/zsh &&  source {{ ansible_env.USER }}/home/.zshrc && sudo chsh -s /bin/zsh && sudo source {{ ansible_env.USER }}/home/.zshrc'
  tags: ohmyzsh
