---

- name: Add Oracle Java Repository
  become: yes
  apt_repository:
    repo: 'ppa:webupd8team/java'
    state: present
  tags: java

- name: Accept Java 8 License
  become: yes
  debconf:
    name: 'oracle-java8-installer'
    question: 'shared/accepted-oracle-license-v1-1'
    value: 'true'
    vtype: 'select'
  tags: java

- name: Install Oracle Java 8
  become: yes
  apt:
    pkg: [
    'oracle-java8-installer',
    'ca-certificates',
    'oracle-java8-set-default'
    ]     
    state: latest
    cache_valid_time: "{{ APT_CACHE_VALID_TIME }}"
  tags: java

