---

- name: Install custom Ubuntu 18.04 LTS
  hosts: localhost
  roles:
    - { role: 00-update-upgrade, become: true }
    - { role: 01-install-basics, become: true }
    - { role: 02-install-libs, become: true }
    - { role: 03-remove-bloatware, become: true }
    - { role: 04-appearance, become: true }
    # - { role: 05-oh-my-zsh, become: true }
    # - { role: 06-tilix, become: true }
    # - { role: 07-clean-system, become: true }
    # - { role: 08-virtualbox, become: true }
    # - { role: 09-vscode, become: true }
    # - { role: 10-chrome, become: true }
    # - { role: 11-git, become: true }
    # - { role: 12-vim, become: true }
    # - { role: 13-vlc, become: true }
    # - { role: 14-java, become: true }
    # - { role: 15-mysql, become: true }
    # - { role: 16-docker, become: true }
    # - { role: 17-ssh, become: true }
    # - { role: 18-spotify, become: true }
    # - { role: 19-openfortigui, become: true }