---

- name: Install custom Ubuntu 18.04 LTS
  hosts: localhost
  roles:
    - { role: 00-update-upgrade, become: true }
    - { role: 01-install-basics, become: true }
    - { role: 02-miniconda3 }    
    - { role: 03-install-libs, become: true }
    - { role: 04-remove-bloatware, become: true }
    - { role: 05-appearance, become: true }
    - { role: 06-oh-my-zsh, oh_my_zsh_theme: agnoster }
    - { role: 07-tilix, become: true }
    - { role: 08-clean-system, become: true }
    - { role: 09-virtualbox, become: true }
    - { role: 10-vscode, become: true }
    - { role: 11-chrome, become: true }
    - { role: 12-git, become: true }
    - { role: 13-java, become: true }
    - { role: 14-docker, become: true }
    - { role: 15-mysql, become: true }
    - { role: 16-ssh, become: true }
    - { role: 17-spotify, become: true }
    - { role: 18-openfortigui, become: true }
