---

- name: Remove examples
  file:
    path: '{{ HOME }}/examples.desktop'
    state: absent

- name: Remove Amazon shit
  file:
    path: /usr/share/applications/ubuntu-amazon-default.desktop
    state: absent

- name: System configuration
  command: "{{ item }}"
  become_user: "{{ ansible_env.USER }}"
  with_items:
    ## Show % battery
    - gsettings set com.canonical.indicator.power show-percentage true
    ## Preferred player Spotify
    - gsettings set com.canonical.indicator.sound interested-media-players "['spotify.desktop']"
    - gsettings set com.canonical.indicator.sound preferred-media-players "['spotify.desktop']"
    ## Interval for notifier on updates
    - gsettings set com.ubuntu.update-notifier regular-auto-launch-interval 0
    ## Set styles for gedit
    - gsettings set org.gnome.gedit.preferences.editor scheme 'cobalt'
    - gsettings set org.gnome.desktop.a11y.magnifier mag-factor 5.0
    - gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'es')]"
    - gsettings set org.gnome.desktop.media-handling autorun-never true
    - gsettings set org.gnome.desktop.privacy remember-recent-files false
    - gsettings set org.gnome.desktop.screensaver lock-enabled false
    - gsettings set org.gnome.desktop.screensaver ubuntu-lock-on-suspend false
    - gsettings set org.gnome.nautilus.list-view default-zoom-level 'small'
    - gsettings set org.gnome.nautilus.preferences executable-text-activation 'ask'
    - gsettings set org.gnome.settings-daemon.plugins.power critical-battery-action 'shutdown'
    - gsettings set org.gnome.settings-daemon.plugins.power idle-dim false
    - gsettings set org.gnome.settings-daemon.plugins.power lid-close-ac-action 'nothing'
    - gsettings set org.gnome.settings-daemon.plugins.power lid-close-battery-action 'nothing'
    - gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 16
    - gsettings set org.gnome.shell.extensions.dash-to-dock dock-position 'BOTTOM'

- name: Ensure unity-control-center and gnome-control-center are installed
  apt:
    pkg: [
        'unity-control-center',
        'gnome-control-center'
    ]
    state: latest
    update_cache: yes
    cache_valid_time: "{{ APT_CACHE_VALID_TIME }}"
