---

- name: Remove examples
  file:
    path: '{{ HOME }}/examples.desktop'
    state: absent

- name: Remove Amazon shit
  file:
    path: /usr/share/applications/ubuntu-amazon-default.desktop
    state: absent

- name: System configuration
  command: "{{ item }}"
  become_user: "{{ ansible_env.USER }}"
  with_items:
    ## Show % battery
    - gsettings set com.canonical.indicator.power show-percentage true
    ## Preferred player Spotify
    - gsettings set com.canonical.indicator.sound interested-media-players "['spotify.desktop']"
    - gsettings set com.canonical.indicator.sound preferred-media-players "['spotify.desktop']"
    ## Interval for notifier on updates
    - gsettings set com.ubuntu.update-notifier regular-auto-launch-interval 0
    ## Set background picture
    - gsettings set org.gnome.desktop.background picture-uri 'https://globalleadershipfoundation.com/assets/files/2015/09/1mp6lukmx2w-stefanus-martanto-setyo-husodo.jpg'
    ## Set default Arc theme
    - gsettings set org.gnome.Terminal.Legacy.Settings theme-variant 'dark'
    - gsettings set org.gnome.desktop.interface gtk-theme 'Arc-Darker'
    - gsettings set org.gnome.shell.extensions.user-theme name 'Arc-Dark'
    ## Set default icons
    - gsettings set org.gnome.desktop.interface icon-theme 'Paper'
    ## Set styles for gedit
    - gsettings set org.gnome.gedit.preferences.editor scheme 'cobalt'
    - gsettings set org.gnome.desktop.a11y.magnifier mag-factor 5.0
    - gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'es')]"
    - gsettings set org.gnome.desktop.media-handling autorun-never true
    - gsettings set org.gnome.desktop.privacy remember-recent-files false
    - gsettings set org.gnome.desktop.screensaver lock-enabled false
    - gsettings set org.gnome.desktop.screensaver ubuntu-lock-on-suspend false
    - gsettings set org.gnome.nautilus.list-view default-zoom-level 'small'
    - gsettings set org.gnome.nautilus.preferences executable-text-activation 'ask'
    - gsettings set org.gnome.settings-daemon.plugins.power critical-battery-action 'shutdown'
    - gsettings set org.gnome.settings-daemon.plugins.power idle-dim false
    - gsettings set org.gnome.settings-daemon.plugins.power lid-close-ac-action 'nothing'
    - gsettings set org.gnome.settings-daemon.plugins.power lid-close-battery-action 'nothing'
    - gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 16
    - gsettings set org.gnome.shell.extensions.dash-to-dock dock-position 'BOTTOM'
    ## Disable WebApps and other shitty integrations
    ## TODO - gsettings set com.canonical.unity.webapps integration-allowed false
    ## TODO - - gsettings set com.canonical.unity.lenses disabled-scopes "['more_suggestions-amazon.scope', 'more_suggestions-u1ms.scope', 'more_suggestions-populartracks.scope', 'music-musicstore.scope', 'more_suggestions-ebay.scope', 'more_suggestions-ubuntushop.scope', 'more_suggestions-skimlinks.scope']"
    ## TODO - - gsettings set com.canonical.unity.lenses remote-content-search 'none'
    ## TODO - gsettings set com.canonical.unity.webapps preauthorized-domains "[]"
    ## TODO - gsettings set com.canonical.Unity.ApplicationsLens display-available-apps false
    ## Backups
    ## TODO - - gsettings set org.gnome.deja-dup backend 'file'
    ## TODO - - gsettings set org.gnome.deja-dup delete-after 365
    ## TODO - - gsettings set org.gnome.deja-dup include-list "['/home/ivan/Development', '/home/ivan/Imágenes']"
    ## TODO - - gsettings set org.gnome.deja-dup periodic-period 1
    ## Proper form factor as netbook
    ## TODO - gsettings set com.canonical.Unity form-factor 'Netbook'

- name: Ensure unity-control-center and gnome-control-center are installed
  apt:
    pkg: [
        'unity-control-center',
        'gnome-control-center'
    ]
    state: latest
    update_cache: yes
    cache_valid_time: "{{ APT_CACHE_VALID_TIME }}"
